export interface KenochemGuideArticle {
  id: string;
  title: string;
  body: string;
}

export interface KenochemGuideSection {
  id: string;
  title: string;
  articles: KenochemGuideArticle[];
}

export const KENOCHEM_GUIDE_SECTIONS: KenochemGuideSection[] = [
  {
    id: 'suite',
    title: 'Suite',
    articles: [
      {
        id: 'suite-purpose',
        title: 'Czym jest Kenochem Suite',
        body: [
          'Kenochem Suite jest glownym pulpitem firmy. Jego zadaniem jest zebranie aplikacji Kenochem w jednym miejscu: katalogu, CRM, operacji finansowych, Talk, magazynu, logistyki, integracji i panelu administracyjnego.',
          '',
          'Najwazniejsza zasada: pracownik loguje sie do Suite i przechodzi miedzy modulami wewnatrz jednego huba. Dzieki temu nie trzeba logowac sie osobno do CRM, Operacji, Talk czy katalogu, jezeli uzywa sie ich przez Suite.',
          '',
          'Osobne adresy aplikacji nadal istnieja jako PWA: katalog, talk, sell/CRM, ops i kolejne narzedzia. Suite ma byc jednak pierwszym miejscem pracy, z ktorego pracownik wybiera co robi dalej.',
        ].join('\n'),
      },
      {
        id: 'suite-navigation',
        title: 'Nawigacja i sidebar aplikacji',
        body: [
          'Lewy sidebar jest launcherem aplikacji. Sekcja Aplikacje zawiera najwazniejsze moduly: Suite, Katalog, CRM, Operacje, Talk, Magazyn i Logistyke.',
          '',
          'Kafle na pulpicie robia to samo, ale w bardziej opisowej formie. Sidebar jest do codziennego szybkiego przechodzenia, pulpit jest do orientacji i startu pracy.',
          '',
          'Miejsce Kolejne narzedzie jest celowo zostawione pod przyszle moduly: kalendarz, dzialy, automatyzacje, raporty, zadania, serwis, reklamacje albo dowolne nowe narzedzie firmowe.',
          '',
          'Ctrl+K otwiera szybkie przejscie. To ma byc najkrotsza droga do sekcji, gdy aplikacji bedzie wiecej.',
        ].join('\n'),
      },
      {
        id: 'suite-pwa',
        title: 'Instalacja PWA i ikony',
        body: [
          'Suite jest aplikacja PWA. Po zainstalowaniu na telefonie lub komputerze otwiera sie jak normalna aplikacja bez paska przegladarki.',
          '',
          'Suite ma osobna ikone, a osobne aplikacje maja swoje ikony: Talk dla czatu, Handel dla CRM, Operacje dla finansow i katalogowa dla produktow/magazynu.',
          '',
          'Na telefonie najlepiej instalowac Suite jako aplikacje glownego dostepu. Osobne PWA maja sens dla pracownikow, ktorzy uzywaja tylko jednego obszaru, np. Talk albo Operacje.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'access',
    title: 'Dostep',
    articles: [
      {
        id: 'login-session',
        title: 'Logowanie i wspolna sesja',
        body: [
          'Logowanie jest oparte o Supabase Auth. Po zalogowaniu Suite zna uzytkownika, role i profil. Moduly osadzone w Suite korzystaja z tej samej sesji.',
          '',
          'Najwazniejsze w praktyce: pracownik powinien zaczynac od Suite, a nie od osobnych domen. Wtedy CRM, Talk, Operacje i katalog dzialaja jako czesci jednej aplikacji.',
          '',
          'Jezeli ktos otworzy osobna domene, np. kenochem-talk.web.app, przegladarka moze traktowac to jako osobna aplikacje. Dlatego docelowo Suite powinien byc glowna brama pracy.',
        ].join('\n'),
      },
      {
        id: 'roles',
        title: 'Role i uprawnienia',
        body: [
          'Role decyduja o tym, co widzi pracownik. Przykladowo nie kazdy musi widziec Operacje finansowe albo panel administracyjny.',
          '',
          'Typowe obszary uprawnien:',
          '- Katalog: przegladanie produktow, zdjec, stanow i danych.',
          '- Magazyn: stany, etykiety, lokalizacje, postep zdjec.',
          '- CRM: klienci, oferty, zamowienia, trasy, lejek.',
          '- Operacje: finanse, raporty, koszty, analizy.',
          '- Talk: komunikacja firmowa.',
          '- Admin: uzytkownicy, role, dostepy i ustawienia.',
          '',
          'Zasada rozwoju: nowe narzedzie powinno miec od razu okreslone kto je widzi i kto moze edytowac dane.',
        ].join('\n'),
      },
      {
        id: 'admin-users',
        title: 'Panel admina i uzytkownicy',
        body: [
          'Panel administracyjny powinien sluzyc do zarzadzania pracownikami, rolami, uprawnieniami i dostepem do aplikacji.',
          '',
          'Docelowo admin powinien moc:',
          '- utworzyc lub zaprosic uzytkownika,',
          '- przypisac role,',
          '- wlaczyc lub wylaczyc moduly,',
          '- sprawdzic aktywnosc konta,',
          '- odebrac dostep po odejsciu pracownika,',
          '- zarzadzac ustawieniami globalnymi firmy.',
          '',
          'Najwazniejsze zabezpieczenie: panel admina nie powinien byc widoczny dla zwyklych uzytkownikow.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'catalog',
    title: 'Katalog',
    articles: [
      {
        id: 'catalog-purpose',
        title: 'Rola katalogu',
        body: [
          'Katalog jest baza produktowa Kenochem. Laczy dane z WAPRO, sklepu, BaseLinkera, zdjec, stanow, EAN, opisow i kategorii.',
          '',
          'Katalog ma pomagac sprzedazy, magazynowi i biuru. Handlowiec ma szybko znalezc produkt, sprawdzic zdjecie, stan, cene i dodac go do zamowienia. Magazyn ma widziec braki zdjec, lokalizacje, etykiety i stany.',
          '',
          'W Suite katalog jest jednym z modulow. W CRM katalog powinien byc zagniezdzony tylko tam, gdzie tworzy sie zamowienie lub oferte.',
        ].join('\n'),
      },
      {
        id: 'catalog-data',
        title: 'Dane produktowe',
        body: [
          'Najwazniejsze pola produktu:',
          '- SKU: podstawowy identyfikator produktu.',
          '- EAN: kod kreskowy, wazny dla magazynu i sklepu.',
          '- katalog: Akcesoria, Produkty lub inny zbior.',
          '- nazwa i nazwa wyswietlana.',
          '- kategoria.',
          '- producent.',
          '- stan magazynowy.',
          '- cena sprzedazy i cena zakupu, jezeli dostepne.',
          '- zdjecie i status zdjecia.',
          '- lokalizacja magazynowa.',
          '- opis, parametry i tagi.',
          '',
          'Dane produktowe powinny byc poprawiane u zrodla tam, gdzie to mozliwe. Frontend moze pomagac w pracy, ale docelowo WAPRO/BaseLinker/sklep powinny byc zrodlem prawdy dla swoich obszarow.',
        ].join('\n'),
      },
      {
        id: 'catalog-knowledge-products',
        title: 'Baza produktowa do wiedzy i AI',
        body: [
          'W public/data/knowledge znajduje sie eksport produktow do formatu JSONL. Kazda linia opisuje produkt i ma pole knowledgeText, gotowe jako chunk do wyszukiwarki wiedzy lub RAG.',
          '',
          'Manifest opisuje liczbe produktow, paczki batch i etapy danych: tozsamosc, opisy, logistyka i media.',
          '',
          'Docelowo asystent firmowy powinien umiec odpowiadac na pytania typu:',
          '- jaki produkt pasuje do danego zastosowania,',
          '- czy mamy stan magazynowy,',
          '- czy produkt ma zdjecie,',
          '- jaki jest EAN/SKU,',
          '- jakie podobne produkty mozna zaproponowac klientowi.',
        ].join('\n'),
      },
      {
        id: 'catalog-sync',
        title: 'Synchronizacja WAPRO i sklepu',
        body: [
          'Stany i czesc danych handlowych pochodza z WAPRO. Sklep i marketplace moga miec swoje opisy, zdjecia, kategorie i ceny.',
          '',
          'Najbezpieczniejszy model:',
          '- WAPRO: stany, dokumenty, kartoteki, rozliczenia.',
          '- BaseLinker: zamowienia marketplace i integracje ecommerce.',
          '- IdoSell/WooCommerce: prezentacja sklepu i tresci sprzedazowe.',
          '- Supabase/Firebase: warstwa aplikacji, cache, CRM, ustawienia, komunikacja.',
          '',
          'Kazdy import powinien miec log: kiedy byl wykonany, ile rekordow zmienil, jakie byly bledy i czy dane sa kompletne.',
        ].join('\n'),
      },
      {
        id: 'catalog-dual',
        title: 'Dwa katalogi: Akcesoria i Produkty',
        body: [
          'Kenochem ma dwa glowne zbiory produktowe:',
          '- Akcesoria (WAPRO): drobnica, osprzet myjni, czesci techniczne — z importu Mag.',
          '- Produkty (BaseLinker / sklep): chemia, kosmetyka, caly eksport sklepu — id shop-SKU.',
          '',
          'Ten sam SKU nie powinien byc liczony podwojnie. Gdy wystepuje w obu zrodlach, wyswietlamy pozycje z wieksza sprzedaza lub preferujemy WAPRO.',
          '',
          'Niebieski znacznik B na karcie oznacza produkt z katalogu BaseLinker (shop) albo reczne powiazanie meta.baselinkerProductId — nie trzeba dopasowywac SKU recznie.',
        ].join('\n'),
      },
      {
        id: 'catalog-search',
        title: 'Wyszukiwarka produktow',
        body: [
          'Wyszukiwarka dziala po SKU, EAN, nazwie, producencie i tagach. Minimum 2 znaki, zeby filtrowac cala siatke.',
          '',
          'Na komputerze pole jest w prawym gornym rogu naglowka — wyniki pojawiaja sie od razu w siatce po lewej (bez rozwijanej listy zaslaniajacej kafelki).',
          '',
          'Na telefonie pasek jest pod naglówkiem i przykleja sie przy przewijaniu. Podpowiedzi (dropdown) sa waskie i wyrównane do prawej.',
          '',
          'Szary X czysci zapytanie i przywraca pelna liste. Ctrl+K fokusuje pole wyszukiwania.',
          '',
          'Wydajnosc: indeks budowany w tle po zaladowaniu katalogu; filtrowanie siatki ma krotkie opoznienie (~90 ms), zeby wpisywanie bylo plynnie.',
        ].join('\n'),
      },
      {
        id: 'catalog-filters',
        title: 'Filtry i sortowanie',
        body: [
          'Pasek filtrow (desktop) lub przycisk Filtry (mobile) pozwala zawezic liste:',
          '- katalog: Wszystkie / Akcesoria / Produkty,',
          '- kategoria i producent,',
          '- stan: na stanie / niski / brak,',
          '- zdjecie: z / bez,',
          '- wiedza produktowa: slaba / dobra (kompletnosc opisu),',
          '- BaseLinker: na BL / poza BL,',
          '- WAPRO Mag: wymaga uzupelnienia (szkielet bez zdjecia).',
          '',
          'Sortowanie domyslne: kategoria + nazwa. Przy aktywnym wyszukiwaniu (≥2 znaki) wyniki sa wg trafnosci, nie alfabetycznie.',
          '',
          'Gestosc siatki (male / srednie / duze kafelki) zapisuje sie w preferencjach konta.',
        ].join('\n'),
      },
      {
        id: 'catalog-badges-actions',
        title: 'Znaczniki, przyciski i tryb edycji',
        body: [
          'Znaczniki na karcie:',
          '- B (niebieski): produkt z eksportu BaseLinker / katalog shop,',
          '- gwiazdka: ulubione (osobny widok),',
          '- etykieta Akcesoria / Produkty przy widoku Wszystkie.',
          '',
          'Przyciski w naglowku katalogu:',
          '- Odswiez: przeladowanie listy z Supabase,',
          '- Sync WAPRO: zlecenie pobrania stanow z serwera Mag (wymaga roli),',
          '- Lens: szukaj po zdjęciu (CLIP vs katalog),',
          '- Edycja: plus/minus stanu na kartach,',
          '- Dodaj: nowy produkt recznie.',
          '',
          'Szczegoly produktu: edycja pol, usuwanie (admin/operator), zdjecia, lokalizacja, sprzedaz z cache Mag.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'crm',
    title: 'CRM',
    articles: [
      {
        id: 'crm-purpose',
        title: 'Cel CRM',
        body: [
          'CRM ma byc centrum pracy handlowca i BOK. Nie ma kopiowac calego katalogu na glowny ekran. Katalog ma pojawiac sie wewnatrz tworzenia oferty lub zamowienia.',
          '',
          'Najwazniejsze moduly CRM:',
          '- baza klientow B2B,',
          '- status klienta: aktywny, uspiony, prospect,',
          '- rejonizacja i przypisanie handlowca,',
          '- lejek sprzedazy,',
          '- tworzenie ofert i zamowien,',
          '- historia zakupow,',
          '- trasy i wizyty,',
          '- kontrola zamowien do akceptacji.',
        ].join('\n'),
      },
      {
        id: 'crm-b2b-clients',
        title: 'Klienci B2B i rejonizacja',
        body: [
          'Klient B2B powinien miec nazwe wyswietlana, nazwe prawna, NIP, adres, notatke, wspolrzedne mapy, przypisany rejon i docelowo opiekuna handlowego.',
          '',
          'Status klienta powinien wynikac z danych:',
          '- aktywny: klient zamawial niedawno,',
          '- uspiony: przekroczyl prog dni bez zamowienia,',
          '- prospect: jest w bazie, ale nie ma historii zamowien.',
          '',
          'Prog "klient cichnie po X dniach" jest ustawieniem firmy. Docelowo powinien byc globalny w Supabase, a nie tylko lokalny.',
        ].join('\n'),
      },
      {
        id: 'crm-orders',
        title: 'Oferty i zamowienia',
        body: [
          'Zamowienie w CRM powinno miec klienta, pozycje, ilosci, ceny, notatke, typ dokumentu i status.',
          '',
          'Proponowany flow:',
          '1. Handlowiec wybiera klienta.',
          '2. Dodaje produkty z zagniezdzonego katalogu.',
          '3. Zapisuje szkic/ofertę albo wysyla zamowienie.',
          '4. BOK lub system integracji przekazuje zamowienie dalej.',
          '5. Status wraca z WAPRO/BaseLinker: potwierdzone, w realizacji, wyslane, dostarczone, rozliczone.',
          '',
          'Na ekranie managera szczegolnie wazne sa zamowienia oczekujace na akceptacje i zamowienia bez przypisanego klienta.',
        ].join('\n'),
      },
      {
        id: 'crm-visits',
        title: 'Trasy i wizyty handlowcow',
        body: [
          'Trasy i wizyty sa sercem handlu terenowego. CRM powinien pokazywac klientow na mapie, plan tygodnia i mozliwosc wejscia do klienta z telefonu.',
          '',
          'Docelowy check-in wizyty:',
          '- handlowiec wybiera klienta,',
          '- rozpoczyna wizyte,',
          '- dodaje notatke, ustalenia i zdjecia jezeli potrzebne,',
          '- tworzy oferte lub zamowienie na miejscu,',
          '- konczy wizyte,',
          '- system zapisuje date, czas, osobe i wynik.',
          '',
          'Na poczatek najwazniejsze jest miec klientow z geolokalizacja i prosty plan wizyt.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'ops',
    title: 'Operacje',
    articles: [
      {
        id: 'ops-purpose',
        title: 'Cel Operacji',
        body: [
          'Operacje sa centrum finansow, rozliczen, kosztow, raportow i analityki firmy. Ten modul nie powinien zawierac zwyklego katalogu produktow na glownym ekranie.',
          '',
          'Operacje maja laczyc dane z ecommerce, handlu terenowego, biura, magazynu, kosztow stalych, faktur, wyciagow, prowizji, marz i raportow.',
          '',
          'Celem jest zastapienie rozproszonych Exceli jednym miejscem, w ktorym mozna wgrywac dane, budowac wlasne plansze i analizowac wynik firmy.',
        ].join('\n'),
      },
      {
        id: 'ops-data-boards',
        title: 'Wlasne zbiory statystyk',
        body: [
          'Uzytkownik powinien moc wgrac plik XLSX/CSV/TSV/TXT i zbudowac z niego plansze analityczna.',
          '',
          'System powinien rozpoznawac kolumny liczbowe, daty i teksty, a potem dawac:',
          '- KPI,',
          '- tabele,',
          '- wykresy,',
          '- filtrowanie,',
          '- grupowanie,',
          '- eksport wynikow,',
          '- zapis wlasnego widoku.',
          '',
          'To jest kierunek "Excel replacement", ale z kontrola danych, lepszym wygladem i wspolnym miejscem pracy.',
        ].join('\n'),
      },
      {
        id: 'ops-sales-channels',
        title: 'Ecommerce i handel terenowy',
        body: [
          'Rozliczenia powinny byc rozdzielone na ecommerce i handel terenowy.',
          '',
          'Ecommerce obejmuje sklepy, marketplace, BaseLinker, koszty prowizji, koszty dostaw, zwroty i kampanie.',
          '',
          'Handel terenowy obejmuje handlowcow, klientow B2B, marze, prowizje, rejony, wizyty, koszty paliwa i wyniki klientow.',
          '',
          'Najlepszy pulpit finansowy powinien pokazac wynik calosci, ale pozwolic zejsc do kanalu, handlowca, klienta, kategorii, okresu i kosztu.',
        ].join('\n'),
      },
      {
        id: 'ops-product-sales',
        title: 'Analiza sprzedazy produktow (Mag WAPRO)',
        body: [
          'Ranking sprzedazy per SKU z cache zsynchronizowanego zbiorczo z Mag. Okresy: 1 / 3 / 6 / 12 miesiecy.',
          '',
          'Liczby ze znakiem: korekty FV z ujemna iloscia odejmuja od sumy. Zysk = suma netto − (cena zakupu × szt.).',
          '',
          'Presety: najwiecej sztuk, najwiekszy obrót, marza, martwy stock, rotacja, wzrost rok do roku (12 m).',
          '',
          'Wykluczenia z sum KPI:',
          '- uslugi wysylki (checkbox),',
          '- koszyk Wyklucz — SKU rozpisane na FV (kwiatki), zeby nie liczyc podwojnie,',
          '- heurystyka „rozpis/skladnik” w nazwie,',
          '- tag sales-exclude-sum lub meta w katalogu.',
          '',
          'Koszyk SKU (Dodaj): porownaj grupe produktow — tabela, wykres i suma Σ.',
          '',
          'Tabela: pelna lista po filtrach, stronicowanie 50/strona, eksport CSV calego widoku. Odswiez z Mag zleca sync na serwerze (kilka minut).',
          '',
          'ABC/XYZ i trend miesieczny wymagaja sync schema v2 (pole monthly w cache).',
        ].join('\n'),
      },
      {
        id: 'ops-sonax',
        title: 'Raport Sonax (przejecie marki)',
        body: [
          'Mierzy obrot od marca 2026 od klientow z historii Sonax (Subiekt), bez overlap z klientami Kenochem sprzed marca.',
          '',
          'Tryby widoku: Standard (czysty Sonax), z mieszanymi, wlasny wybor z listy wykluczonych.',
          '',
          'Overlap to klienci, ktorzy kupowali u Sonax i u Kenochem przed przejeciem — domyslnie poza KPI ~104 tys. Dodanie 2 najwiekszych overlap daje ~197 tys.',
          '',
          'Dane: sonax-reconcile.json + eksporty WAPRO z serwera. Bez wapro-kenochem-przed.tsv overlap nie jest wykluczany.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'talk',
    title: 'Talk',
    articles: [
      {
        id: 'talk-purpose',
        title: 'Czat firmowy',
        body: [
          'Talk jest komunikatorem Kenochem. Ma dzialac jak normalny czat firmowy: lista rozmow, rozmowa, reakcje, odpowiedzi, pliki, gify, potwierdzenia odczytu i powiadomienia push.',
          '',
          'W Suite Talk otwiera sie jako duzy panel, ale korzysta z tej samej sesji uzytkownika. Osobna aplikacja Talk PWA nadal moze byc instalowana na telefonie.',
          '',
          'Najwazniejszy standard: rozmowy musza byc czytelne na jasnym i ciemnym motywie oraz wygodne na telefonie.',
        ].join('\n'),
      },
      {
        id: 'talk-push',
        title: 'Powiadomienia push',
        body: [
          'Powiadomienia push wymagaja zgody uzytkownika, aktywnej subskrypcji push, poprawnej pary VAPID i dzialajacej funkcji Supabase odpowiedzialnej za wysylke.',
          '',
          'Test push moze przejsc, a wiadomosc nadal nie wyslac powiadomienia, jezeli brakuje polaczenia miedzy zapisem wiadomosci a wywolaniem funkcji push.',
          '',
          'Docelowo powiadomienie powinno zawierac nazwe nadawcy, fragment wiadomosci, ikone Talk, avatar nadawcy jezeli system ma publiczny URL avatara, oraz klikac bezposrednio do rozmowy.',
        ].join('\n'),
      },
      {
        id: 'talk-mobile',
        title: 'Telefon i gesty',
        body: [
          'Na telefonie czat powinien zachowywac sie jak Messenger/WhatsApp:',
          '- po wejściu w rozmowe przewija na dol,',
          '- przycisk cofania wraca do listy rozmow, nie wyrzuca z aplikacji,',
          '- przytrzymanie wiadomosci otwiera reakcje i akcje,',
          '- pole pisania nie powinno zostawiac pustej przestrzeni nad klawiatura,',
          '- powiadomienie otwiera konkretna rozmowe.',
          '',
          'Te zachowania sa krytyczne, bo pracownicy beda korzystac z Talk glownie na telefonach.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'warehouse',
    title: 'Magazyn',
    articles: [
      {
        id: 'warehouse-purpose',
        title: 'Magazyn i stany',
        body: [
          'Modul magazynu sluzy do pracy ze stanami, etykietami, zdjeciami, lokalizacja i kompletnością kart produktowych.',
          '',
          'Najwazniejsze widoki magazynowe:',
          '- produkty bez zdjec,',
          '- niskie stany,',
          '- kolejka etykiet,',
          '- lokalizacje magazynowe,',
          '- postep uzupelniania katalogu.',
        ].join('\n'),
      },
      {
        id: 'warehouse-locations',
        title: 'Lokalizacje SKU i mapa hali',
        body: [
          'Lokalizacja SKU opisuje, gdzie fizycznie lezy produkt. Dobra lokalizacja powinna byc czytelna dla magazynu i dla handlowca, ktory chce szybko sprawdzic dostepnosc towaru.',
          '',
          'Proponowany schemat adresu:',
          '- strefa: np. DRO, CHE, PAK, WYS,',
          '- alejka albo regal,',
          '- polka lub poziom,',
          '- pojemnik albo miejsce paletowe.',
          '',
          'Mapa 2.5D jest widokiem pomocniczym. Ma szybko pokazac uklad hali i kierunek szukania produktu. Zrodlem prawdy sa jednak zapisane elementy planu oraz przypisane lokalizacje SKU.',
          '',
          'Docelowo klikniecie produktu powinno podswietlic regal, polke lub pojemnik na mapie, podobnie jak w aplikacjach sklepowych pokazujacych lokalizacje produktu na regale.',
        ].join('\n'),
      },
      {
        id: 'warehouse-labels',
        title: 'Etykiety polek',
        body: [
          'Etykiety polek pomagaja fizycznie uporzadkowac magazyn. Produkt mozna dodac do kolejki etykiet z karty produktu lub widoku etykiet.',
          '',
          'Dobra etykieta powinna zawierac SKU, nazwe, kod kreskowy/EAN jezeli jest, kategorie i informacje potrzebne magazynowi.',
        ].join('\n'),
      },
      {
        id: 'warehouse-photos',
        title: 'Zdjecia produktow',
        body: [
          'Zdjecia sa wazne dla katalogu, sklepu, handlowcow i klientow. Widok brakow zdjec powinien pomagac systematycznie uzupelniac produkty.',
          '',
          'Dobre zdjecie produktowe powinno byc ostre, miec jasne tlo, pokazywac prawdziwy produkt i byc przypisane do poprawnego SKU.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'calendar',
    title: 'Kalendarz',
    articles: [
      {
        id: 'calendar-purpose',
        title: 'Cel kalendarza firmowego',
        body: [
          'Kenochem Kalendarz ma porzadkowac wspolny plan firmy: wizyty handlowcow, dostawy, raporty, odprawy, zadania, synchronizacje i terminy finansowe.',
          '',
          'Kalendarz nie powinien byc tylko lista dat. Ma laczyc sie z innymi aplikacjami:',
          '- CRM: wizyty, klienci, trasy i follow-upy,',
          '- Magazyn: dostawy, kompletacje, inwentaryzacje,',
          '- Operacje: raporty, platnosci, zamkniecia miesiaca,',
          '- Talk: odprawy, komunikaty zespolu, przypomnienia.',
          '',
          'Na teraz wydarzenia sa lokalne w aplikacji. Docelowo powinny byc zapisywane globalnie w Supabase, z uprawnieniami i synchronizacja Google/Outlook.',
        ].join('\n'),
      },
      {
        id: 'calendar-events',
        title: 'Dodawanie i edycja wydarzen',
        body: [
          'Wydarzenie powinno miec tytul, date, godzine, osobe odpowiedzialna, miejsce i notatke. Typ wydarzenia nadaje kolor oraz wskazuje, z jaka aplikacja moze byc powiazane.',
          '',
          'Dobra praktyka:',
          '- wpisuj konkretny tytul, np. "Wizyta: Auto-Myjnia Kowalski",',
          '- dodawaj osobe lub dzial odpowiedzialny,',
          '- w notatce zapisuj ustalenia i nastepny krok,',
          '- dla wizyt handlowych podpinaj klienta z CRM, gdy integracja bedzie gotowa.',
          '',
          'Kalendarz ma dzialac jak Google Calendar: wybierasz dzien, tworzysz wpis, edytujesz szczegoly i wracasz do siatki bez szukania formularza na dole strony.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'integrations',
    title: 'Integracje',
    articles: [
      {
        id: 'integrations-map',
        title: 'Mapa systemow',
        body: [
          'Kenochem korzysta z kilku zrodel danych. Suite powinien je laczyc, ale nie mieszac odpowiedzialnosci.',
          '',
          'Proponowana mapa:',
          '- WAPRO Mag/Fakir: magazyn, dokumenty, rozliczenia, platnosci.',
          '- BaseLinker: zamowienia ecommerce i marketplace.',
          '- IdoSell/WooCommerce: sklep, opisy, kategorie, prezentacja produktow.',
          '- Supabase: uzytkownicy, CRM, czat, ustawienia, dane aplikacyjne.',
          '- Firebase Hosting: publikacja aplikacji PWA.',
          '- pliki XLSX/CSV: importy pomocnicze, raporty i analizy.',
        ].join('\n'),
      },
      {
        id: 'integrations-rules',
        title: 'Zasady bezpiecznych integracji',
        body: [
          'Kazda integracja powinna miec:',
          '- zrodlo prawdy,',
          '- harmonogram synchronizacji,',
          '- log wykonania,',
          '- liczbe dodanych/zmienionych/usunietych rekordow,',
          '- widoczne bledy,',
          '- mozliwosc testu bez zmiany danych,',
          '- jasna informacje kto moze uruchomic sync.',
          '',
          'Nie wolno ukrywac bledow importu. Jezeli dane sa niepelne, panel powinien pokazac stan i date ostatniej poprawnej synchronizacji.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'deployment',
    title: 'Wdrozenia',
    articles: [
      {
        id: 'deployment-products',
        title: 'Aplikacje i adresy',
        body: [
          'Glowne aplikacje:',
          '- Suite: https://kenochem-f4a5b.web.app/',
          '- Katalog: https://kenochem-katalog.web.app/',
          '- Talk: https://kenochem-talk.web.app/',
          '- CRM/Handel: https://kenochem-sell.web.app/',
          '- Operacje: https://kenochem-ops.web.app/',
          '',
          'Po malych zmianach przyjete jest szybkie wdrozenie na Firebase, zeby od razu sprawdzic efekt na telefonie i komputerze.',
        ].join('\n'),
      },
      {
        id: 'deployment-checklist',
        title: 'Checklist przed deployem',
        body: [
          'Minimalna lista kontroli:',
          '1. Build odpowiedniego wariantu przechodzi bez bledu.',
          '2. Manifest PWA wskazuje poprawne ikony.',
          '3. Publiczny URL zwraca 200 OK.',
          '4. Zmiana nie przywraca katalogu tam, gdzie ma byc osobny modul.',
          '5. Mobile ma czytelne teksty i nie ma nachodzacych elementow.',
          '6. Nowe funkcje sa dostepne tylko dla rol, ktore powinny je widziec.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'help',
    title: 'Podpowiedzi',
    articles: [
      {
        id: 'help-context',
        title: 'Ikona i przy trudniejszych funkcjach',
        body: [
          'Ikona "i" obok narzedzia oznacza szybka podpowiedz kontekstowa. Po najechaniu myszka, fokusie klawiatura albo tapnieciu na telefonie pokazuje krotkie wyjasnienie: co to jest, kiedy tego uzyc i co oznaczaja dane.',
          '',
          'Zasada projektowa:',
          '- tooltip ma pomagac podjac decyzje, nie powtarzac etykiete przycisku,',
          '- pelne instrukcje trafiaja do Bazy wiedzy,',
          '- trudne pojecia powinny miec i przy pierwszym uzyciu na ekranie,',
          '- jezeli funkcja dotyka danych finansowych, syncu, uprawnien albo integracji, powinna miec podpowiedz.',
          '',
          'Dzieki temu nowe osoby moga pracowac w systemie bez pytania za kazdym razem, co oznacza dane narzedzie.',
        ].join('\n'),
      },
      {
        id: 'help-data-quality',
        title: 'Jak czytac status danych',
        body: [
          'W aplikacjach Kenochem dane beda pochodzic z wielu zrodel: WAPRO, BaseLinker, sklep, Supabase, pliki raportowe i reczne wpisy.',
          '',
          'Najwazniejsze pojecia:',
          '- zrodlo prawdy: system, ktory jest najwazniejszy dla danego typu danych,',
          '- import reczny: dane wgrane plikiem przez uzytkownika,',
          '- sync: automatyczne lub zlecone pobranie danych ze zrodla,',
          '- status danych: informacja czy dane sa kompletne, przestarzale, reczne lub wymagaja sprawdzenia.',
          '',
          'Przy liczbach finansowych i magazynowych zawsze trzeba patrzec na date ostatniego importu oraz zakres danych.',
        ].join('\n'),
      },
      {
        id: 'help-glossary',
        title: 'Slownik roboczy Kenochem',
        body: [
          'SKU: wewnetrzny indeks produktu.',
          'EAN: kod kreskowy produktu.',
          'PWA: aplikacja webowa instalowana na telefonie lub komputerze.',
          'WAPRO: system magazynowo-ksiegowy i wazne zrodlo stanow, dokumentow i rozliczen.',
          'BaseLinker: hub zamowien ecommerce i marketplace.',
          'Supabase: baza aplikacyjna, uzytkownicy, CRM, czat, ustawienia i dane robocze.',
          'Firebase Hosting: publikacja aplikacji webowych Kenochem.',
          'RAG: asystent AI odpowiadajacy na podstawie naszej bazy wiedzy i danych.',
          'Cashflow: przeplywy pieniezne firmy, czyli wplywy i wydatki w czasie.',
          'Lejek sprzedazy: etapy pracy nad szansa sprzedazy od kontaktu do wygranej/przegranej.',
          'Tag B: produkt z katalogu BaseLinker (shop) — niebieski znacznik na karcie.',
          'Kwiatki / rozpis: pozycje pomocnicze na FV — wykluczaj z sum sprzedazy w Ops.',
          'ABC: klasa A/B/C wg udzialu w obrocie (A ≈ pierwsze 80% sumy netto).',
          'XYZ: stabilnosc popytu — X regularny, Z skokowy.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'standards',
    title: 'Standard pracy',
    articles: [
      {
        id: 'standards-ui',
        title: 'Standard UI Kenochem',
        body: [
          'UI Kenochem powinien byc praktyczny, czytelny i szybki. To sa narzedzia pracy, nie landing page.',
          '',
          'Zasady:',
          '- duze hero tylko tam, gdzie pomaga zrozumiec start,',
          '- w narzedziach gesty i akcje maja byc oczywiste,',
          '- sidebar powinien porzadkowac aplikacje,',
          '- dane maja byc latwe do skanowania,',
          '- jasny i ciemny motyw musza miec dobry kontrast,',
          '- mobile nie moze byc wersja "upchnieta", tylko realnym trybem pracy.',
        ].join('\n'),
      },
      {
        id: 'standards-data',
        title: 'Standard danych',
        body: [
          'Dane firmowe musza byc spojne. Kazdy rekord powinien miec identyfikator, date aktualizacji i jasne zrodlo.',
          '',
          'Dla produktow najwazniejsze sa SKU i EAN. Dla klientow NIP i nazwa prawna. Dla zamowien klient, status, pozycje i wartosc. Dla finansow okres, kanal, kategoria kosztu i zrodlo.',
          '',
          'Jezeli system nie zna danych, lepiej pokazac brak lub wymagane uzupelnienie niz zgadywac.',
        ].join('\n'),
      },
      {
        id: 'standards-roadmap',
        title: 'Kierunek rozwoju',
        body: [
          'Najwazniejsze kolejne kierunki:',
          '- globalne ustawienia firmy w Supabase,',
          '- pelny panel admina Suite,',
          '- integracje WAPRO/BaseLinker/IdoSell z logami,',
          '- centrum raportow w Operacjach,',
          '- rozliczanie handlowcow i rejonow,',
          '- prawdziwa mapa wizyt i check-in,',
          '- firmowy asystent wiedzy oparty o dokumentacje i baze produktowa,',
          '- automatyczne alerty: platnosci, braki, cichnacy klienci, zalegle zamowienia.',
        ].join('\n'),
      },
    ],
  },
];

export function findKenochemGuideArticle(id: string) {
  for (const section of KENOCHEM_GUIDE_SECTIONS) {
    const article = section.articles.find((a) => a.id === id);
    if (article) return { section, article };
  }
  return null;
}
