-- Globalny numer kolejny zlecen WAPRO (do numeru zamowienia klienta: H + inicjal handlowca + inicjal firmy + 00001)
-- Dashboard -> SQL Editor -> Run
alter table public.wapro_order_requests
  add column if not exists seq bigint generated by default as identity;
