-- Diagnostyka + test JOIN (Kenochem: ID_KATEGORII)
--   sqlcmd -S DESKTOP-PANA1RQ -d WAPRO -E -W -i C:\katalog-sync\wapro-manufacturer-probe.sql

SET NOCOUNT ON;

PRINT '=== TOP 10: SKU + marka (KATEGORIA_ARTYKULU) ===';
SELECT TOP 10
  LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) AS sku,
  LTRIM(RTRIM(k.NAZWA)) AS manufacturer,
  a.ID_KATEGORII
FROM dbo.ARTYKUL a WITH (NOLOCK)
LEFT JOIN dbo.KATEGORIA_ARTYKULU k WITH (NOLOCK)
  ON k.ID_KATEGORII = a.ID_KATEGORII
WHERE a.INDEKS_KATALOGOWY IS NOT NULL
  AND LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) <> ''
ORDER BY a.INDEKS_KATALOGOWY;

PRINT '=== TOP 10: SKU + marka (drzewo ID_KATEGORII_TREE) ===';
SELECT TOP 10
  LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) AS sku,
  LTRIM(RTRIM(t.NAZWA)) AS manufacturer_tree,
  a.ID_KATEGORII_TREE
FROM dbo.ARTYKUL a WITH (NOLOCK)
LEFT JOIN dbo.KATEGORIA_ARTYKULU_TREE t WITH (NOLOCK)
  ON t.ID_KATEGORII = a.ID_KATEGORII_TREE
WHERE a.INDEKS_KATALOGOWY IS NOT NULL
  AND LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) <> ''
ORDER BY a.INDEKS_KATALOGOWY;

PRINT '=== Statystyka: ile SKU ma pusta marke ===';
SELECT
  SUM(CASE WHEN k.NAZWA IS NULL OR LTRIM(RTRIM(k.NAZWA)) = '' THEN 1 ELSE 0 END) AS bez_marki,
  COUNT(*) AS razem
FROM dbo.ARTYKUL a WITH (NOLOCK)
LEFT JOIN dbo.KATEGORIA_ARTYKULU k WITH (NOLOCK)
  ON k.ID_KATEGORII = a.ID_KATEGORII
WHERE a.INDEKS_KATALOGOWY IS NOT NULL
  AND LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) <> '';
