-- Zbiorcza sprzedaż Mag WAPRO per SKU (12 mies.) — sync-wapro-stock-server.ps1 -SalesSyncOnly
-- Ilość i netto: SUM ze znakiem (korekty / zwroty ujemne), bez ABS.

SET NOCOUNT ON;
DECLARE @d1 int = CAST(CAST(DATEADD(month, -1, CAST(GETDATE() AS date)) AS datetime) AS int) + 36163;
DECLARE @d3 int = CAST(CAST(DATEADD(month, -3, CAST(GETDATE() AS date)) AS datetime) AS int) + 36163;
DECLARE @d6 int = CAST(CAST(DATEADD(month, -6, CAST(GETDATE() AS date)) AS datetime) AS int) + 36163;
DECLARE @d12 int = CAST(CAST(DATEADD(month, -12, CAST(GETDATE() AS date)) AS datetime) AS int) + 36163;

SELECT
  LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) AS sku,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d1 THEN pd.ILOSC ELSE 0 END), 0) AS DECIMAL(18, 3)) AS qty_1m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d3 THEN pd.ILOSC ELSE 0 END), 0) AS DECIMAL(18, 3)) AS qty_3m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d6 THEN pd.ILOSC ELSE 0 END), 0) AS DECIMAL(18, 3)) AS qty_6m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d12 THEN pd.ILOSC ELSE 0 END), 0) AS DECIMAL(18, 3)) AS qty_12m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d1 THEN pd.ILOSC * ISNULL(pd.CENA_NETTO, 0) ELSE 0 END), 0) AS DECIMAL(18, 2)) AS net_1m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d3 THEN pd.ILOSC * ISNULL(pd.CENA_NETTO, 0) ELSE 0 END), 0) AS DECIMAL(18, 2)) AS net_3m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d6 THEN pd.ILOSC * ISNULL(pd.CENA_NETTO, 0) ELSE 0 END), 0) AS DECIMAL(18, 2)) AS net_6m,
  CAST(ISNULL(SUM(CASE WHEN dh.DATA_WYSTAWIENIA >= @d12 THEN pd.ILOSC * ISNULL(pd.CENA_NETTO, 0) ELSE 0 END), 0) AS DECIMAL(18, 2)) AS net_12m,
  CAST(ISNULL(MAX(CASE WHEN dh.DATA_WYSTAWIENIA >= @d12 AND pd.ILOSC <> 0 THEN dh.DATA_WYSTAWIENIA END), 0) AS INT) AS last_data_int
FROM dbo.POZYCJA_DOKUMENTU_MAGAZYNOWEGO pd WITH (NOLOCK)
INNER JOIN dbo.DOKUMENT_HANDLOWY dh WITH (NOLOCK)
  ON dh.ID_DOKUMENTU_HANDLOWEGO = pd.ID_DOK_HANDLOWEGO
INNER JOIN dbo.ARTYKUL a WITH (NOLOCK) ON a.ID_ARTYKULU = pd.ID_ARTYKULU
WHERE pd.RODZAJ_POZYCJI = 'R'
  AND dh.DATA_WYSTAWIENIA >= @d12
  AND a.INDEKS_KATALOGOWY IS NOT NULL
  AND LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) <> ''
GROUP BY LTRIM(RTRIM(a.INDEKS_KATALOGOWY));
