-- Diagnostyka schematu WAPRO — BEZ zakladanych nazw kolumn JOIN.
-- Uruchom na RDP:
--   sqlcmd -S DESKTOP-PANA1RQ -d WAPRO -E -W -i C:\katalog-sync\wapro-manufacturer-probe.sql

SET NOCOUNT ON;

PRINT '=== ARTYKUL: kolumny z KATEG / INDEKS ===';
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ARTYKUL'
  AND (
    COLUMN_NAME LIKE '%KATEG%'
    OR COLUMN_NAME LIKE '%INDEKS%'
    OR COLUMN_NAME LIKE '%KAT_%'
  )
ORDER BY COLUMN_NAME;

PRINT '=== KATEGORIA_ARTYKULU: wszystkie kolumny ===';
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'KATEGORIA_ARTYKULU'
ORDER BY ORDINAL_POSITION;

PRINT '=== KATEGORIA_ARTYKULU_TREE: wszystkie kolumny ===';
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'KATEGORIA_ARTYKULU_TREE'
ORDER BY ORDINAL_POSITION;

PRINT '=== WIDOK_KATEGORIAARTYKULU: kolumny ===';
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'WIDOK_KATEGORIAARTYKULU'
ORDER BY ORDINAL_POSITION;

PRINT '=== Probka KATEGORIA_ARTYKULU (TOP 8) ===';
SELECT TOP 8 * FROM dbo.KATEGORIA_ARTYKULU WITH (NOLOCK);

PRINT '=== Probka ARTYKUL — tylko kolumny kategorii (dynamicznie: uruchom recznie po znaniu nazw) ===';
-- Po probe powyzej uruchom recznie np.:
-- SELECT TOP 3 INDEKS_KATALOGOWY, <TWOJA_KOLUMNA_KATEG> FROM dbo.ARTYKUL;
