-- Eksport producenta (kategoria WAPRO Mag = marka) + SKU.
-- Kenochem WAPRO: ARTYKUL.ID_KATEGORII = KATEGORIA_ARTYKULU.ID_KATEGORII
--
-- Test TOP 5:
--   sqlcmd -S DESKTOP-PANA1RQ -d WAPRO -E -W -Q "SET NOCOUNT ON; SELECT TOP 5 LTRIM(RTRIM(a.INDEKS_KATALOGOWY)), LTRIM(RTRIM(k.NAZWA)) FROM dbo.ARTYKUL a LEFT JOIN dbo.KATEGORIA_ARTYKULU k ON k.ID_KATEGORII = a.ID_KATEGORII WHERE a.INDEKS_KATALOGOWY IS NOT NULL"
--
-- Eksport CSV:
--   sqlcmd -S DESKTOP-PANA1RQ -d WAPRO -E -W -h-1 -s";" -f 65001 -i C:\katalog-sync\wapro-manufacturer-export.sql -o C:\katalog-sync\wapro-manufacturers.csv

SET NOCOUNT ON;

SELECT
  LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) AS sku,
  LTRIM(RTRIM(k.NAZWA)) AS wapro_manufacturer
FROM dbo.ARTYKUL a WITH (NOLOCK)
LEFT JOIN dbo.KATEGORIA_ARTYKULU k WITH (NOLOCK)
  ON k.ID_KATEGORII = a.ID_KATEGORII
WHERE a.INDEKS_KATALOGOWY IS NOT NULL
  AND LTRIM(RTRIM(a.INDEKS_KATALOGOWY)) <> ''
ORDER BY sku;
