#!/usr/bin/env python3
"""Buduje indeks SKU BaseLinker do tagu „B” w katalogu / Ops (z CSV Base__Produkty__)."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from lib.baselinker_export import find_latest_baselinker_csv, load_enrichment_index  # noqa: E402

OUT_TS = ROOT / "src" / "lib" / "baselinkerSkuIndex.generated.ts"
OUT_JSON = ROOT / "public" / "data" / "baselinker-sku-index.json"


def norm_sku(s: str) -> str:
    s = re.sub(r"[^A-Z0-9]", "", (s or "").upper())
    m = re.match(r"^([A-Z]+)0*([0-9]+)$", s)
    if m:
        return m.group(1) + str(int(m.group(2)))
    return s


def main() -> None:
    csv_path = Path(sys.argv[1]) if len(sys.argv) > 1 else find_latest_baselinker_csv()
    if not csv_path or not csv_path.exists():
        raise SystemExit("Brak CSV Base__Produkty__*.csv w Downloads")

    index = load_enrichment_index(csv_path)
    sku_to_id: dict[str, str] = {}
    all_keys: set[str] = set()

    for sku, rec in index.items():
        bl_id = (rec.baselinker_product_id or "").strip()
        if not bl_id:
            continue
        for key in {sku, norm_sku(sku)}:
            if not key:
                continue
            all_keys.add(key)
            sku_to_id[key] = bl_id

    keys_sorted = sorted(all_keys)
    payload = {
        "generatedAt": __import__("datetime").datetime.now().isoformat(timespec="seconds"),
        "sourceCsv": csv_path.name,
        "skuCount": len(keys_sorted),
        "skuToId": sku_to_id,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "/** Auto-generated by scripts/build-baselinker-sku-index.py — do not edit */",
        f"// Source: {csv_path.name} · {len(index)} produktów · {len(keys_sorted)} kluczy SKU",
        "",
        "export const BASELINKER_SKU_TO_ID: Record<string, string> = {",
    ]
    for k in keys_sorted:
        lines.append(f'  {json.dumps(k)}: {json.dumps(sku_to_id[k])},')
    lines.append("};")
    lines.append("")
    lines.append("export const BASELINKER_SKUS = new Set<string>(Object.keys(BASELINKER_SKU_TO_ID));")
    lines.append("")

    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: {len(index)} SKU z CSV -> {len(keys_sorted)} kluczy")
    print(f"  {OUT_TS.relative_to(ROOT)}")
    print(f"  {OUT_JSON.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
